services:
  init: &init
    image: wlcamargo/spark-dev:3.5.0
    container_name: init
    environment:
      - SPARK_NO_DAEMONIZE=true
    networks:
      - spark-network

  jupyter:
    image: wlcamargo/jupyter-light
    container_name: jupyter
    user: root
    command: jupyter lab --ip 0.0.0.0 --port 8888 --no-browser --NotebookApp.token='' --NotebookApp.password='' --allow-root
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    extra_hosts:
      - "host.docker.internal:host-gateway"  
    volumes:
      #- .data/jobs_spark/spark/util:/util
      #- .data/jobs_spark/spark/env:/env 
      - ./app-pyspark:/home/jovyan/work  
    ports:
      - 8888:8888
      - 4040:4040
    networks:
      - spark-network
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

  spark-master:
    <<: *init
    container_name: spark-master
    ports:
      - 8080:8080
    expose:
      - 7077
    command: /opt/spark/sbin/start-master.sh
    networks:
      - spark-network
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
  
  spark-worker:
    <<: *init
    container_name: spark-worker
    command: /opt/spark/sbin/start-worker.sh spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - spark-network
    deploy:
      replicas: 3
      placement:
        constraints: [node.role == worker]

networks:
  spark-network:
    driver: overlay